/** Headless-test hooks (window.__studio) — the playtest drives the editor
 *  through these instead of clicking DOM. */
import type { EntityKind } from './model.js';

export interface StudioDebug {
  ready: () => boolean;
  addEntity: (kind: EntityKind, x: number, y: number) => string;
  entityCount: () => number;
  select: (name: string) => boolean;
  setProp: (key: string, value: unknown) => boolean;
  getEntity: (name: string) => Record<string, unknown> | null;
  play: () => void;
  stop: () => void;
  playing: () => boolean;
  playEntityCount: () => number;
  setScript: (code: string) => void;
  applyScriptNow: (code: string) => void;
  addScene: (name: string) => string;
  sceneCount: () => number;
  switchSceneByName: (name: string) => boolean;
  sceneName: () => string;
  exportJson: () => string;
  importJson: (json: string) => void;
  projectName: () => string;
  setStory: (lines: string[]) => boolean;
  templateCount: () => number;
  loadTemplate: (id: string) => boolean;
  playScore: () => number;
  playVisibleCount: () => number;
  gameIsOver: () => boolean;
  skillNodeCount: () => number;
  skillPoints: () => number;
  skillAddPoints: (n: number) => void;
  skillUnlock: (id: string) => boolean;
  skillUnlocked: () => string[];
  setMultiplayer: (b: boolean) => void;
  netHost: () => Promise<string>;
  netJoin: (code: string) => Promise<void>;
  netCode: () => string | null;
  netIsHost: () => boolean;
  netPlayerCount: () => number;
  netRemoteCount: () => number;
  netRemotePos: () => { x: number; y: number } | null;
  netSetState: (k: string, v: unknown) => void;
  netGetState: (k: string) => unknown;
  setTile: (c: number, r: number, ch: string, layer?: string) => void;
  tileAt: (c: number, r: number, layer?: string) => string;
  setTileMode: (ch: string | null) => void;
  playHasTiles: () => boolean;
  playHasOverTiles: () => boolean;
  /** 💾 save slots */
  saveSlots: () => {
    slot: number;
    used: boolean;
    level: string;
    completed: string[];
    coins: number;
    playedSecs: number;
    updated: number;
  }[];
  slotNow: () => number;
  slotPick: (n: number, fresh: boolean) => void;
  slotErase: (n: number) => void;
  levelDone: () => void;
  unlockedLevels: () => string[];
  /** 🛰 host authority */
  netRole: () => string;
  netWorld: () => { t: number; mobs: { n: string; x: number; y: number; hp: number }[]; shots: { x: number; y: number }[] } | null;
  netLink: () => string;
  netRequestHit: (name: string, dmg: number) => void;
  setView: (v: 'top' | 'depth') => void;
  setGravity: (g: boolean) => void;
  setWorldSize: (w: number, h: number) => void;
  worldSize: () => { w: number; h: number };
  cameraX: () => number;
  setFramePreview: (m: 'off' | 'landscape' | 'portrait') => void;
  framePreview: () => 'off' | 'landscape' | 'portrait';
  mobCount: () => number;
  mobHp: (name: string) => number;
  heartsNow: () => number;
  xpNow: () => number;
  levelNow: () => number;
  abilityCount: () => number;
  fireAbility: (name: string) => boolean;
  bossBarVisible: () => boolean;
  playerZ: () => number;
  shotsFired: () => number;
  mobEnraged: (name: string) => boolean;
  chatBridged: () => boolean;
  coinsNow: () => number;
  setEvents: (name: string, events: unknown) => boolean;
  originNow: () => unknown;
  setOriginGitHub: (o: { owner: string; repo: string; branch: string; path: string }) => string;
  setOriginDevice: () => void;
  whereText: () => string;
  syncState: () => string;
  projectHasSecrets: () => string[];
  setDialogue: (name: string, tree: unknown) => boolean;
  tapEntity: (name: string) => boolean;
  dialogueAt: () => string | null;
  dialogueOptions: () => string[];
  dialoguePick: (i: number) => boolean;
  dialogueAdvance: () => boolean;
  playerGrounded: () => boolean;
  openHud: () => void;
  hudNow: () => unknown;
  hudMove: (part: string, x: number, y: number) => { anchor: string; dx: number; dy: number };
  hudSet: (part: string, patch: Record<string, unknown>) => void;
  hudSafe: (top: number, bottom: number) => void;
  hudScreenPos: (part: string) => { x: number; y: number; visible: boolean } | null;
  undo: () => boolean;
  redo: () => boolean;
  historyState: () => { canUndo: boolean; canRedo: boolean; undoLabel: string; redoLabel: string };
  historyDepth: () => { past: number; future: number };
  playSolo: () => void;
  menuVisible: () => boolean;
  gamePaused: () => boolean;
  openAbilities: (id?: string) => void;
  createAbility: (name: string) => string;
  setAbility: (id: string, patch: Record<string, unknown>) => boolean;
  grantAbility: (entity: string, id: string, on: boolean) => boolean;
  abilitiesOf: (entity: string) => string[];
  abilityIds: () => string[];
  setSkillTreeDb: (id: string, tree: unknown) => void;
  setActorSkillTree: (entity: string, treeId: string) => boolean;
  assetList: () => { id: string; bytes: number; users: number }[];
  assetBytes: () => number;
  importAsset: (dataUrl: string) => string;
  assignAsset: (entity: string, id: string) => boolean;
  deleteAsset: (id: string) => number;
  unusedAssets: () => string[];
  importReject: (name: string, mime: string) => string | null;
  openAssets: () => void;
  genGame: (params: unknown) => string[];
  skillBranchCount: () => number;
  skillRank: (id: string) => number;
  skillInvest: (id: string) => boolean;
  skillCanInvest: (id: string) => string;
  skillSpentIn: (branch: string) => number;
  skillRespec: () => number;
  skillOpen: () => void;
  skillIsOpen: () => boolean;
  skillLayout: () => { mode: string; cols: number; cell: number; fit: number };
  bindKey: (action: string, key: string) => boolean;
  unbindKey: (action: string, key: string) => boolean;
  keysOf: (action: string) => string[];
  addAction: (id: string) => boolean;
  removeAction: (id: string) => boolean;
  keyConflicts: () => string[];
  resetControls: () => void;
  getPlayPos: (name: string) => { x: number; y: number };
  apiSearch: (q: string) => string[];
  apiInsert: (name: string) => boolean;
  codeText: () => string;
  scriptError: () => string;
  setLevelEvents: (events: unknown) => boolean;
  levelEventCount: () => number;
  tapLevel: () => boolean;
  switchIsOn: (name: string) => boolean;
  musicNow: () => string | null;
  vfxCount: () => number;
  setOutfit: (name: string, opts: { hat?: string; held?: string }) => void;
  outfitOf: (name: string) => { hat: string; held: string } | null;
  flowDropOff: (nodeId: string) => boolean;
  paletteQuery: (q: string) => string[];
  paletteVisible: () => string[];
  paletteMove: (d: number) => string | null;
  paletteHighlighted: () => string | null;
  paletteCommit: (id?: string) => boolean;
  paletteClose: () => void;
  flowNodeIds: () => string[];
  flowLink: (fromName: string, toName: string) => boolean;
  setDbItems: (items: unknown) => void;
  setLocales: (locales: unknown) => void;
  itemCountOf: (id: string) => number;
  giveItem: (id: string) => boolean;
  useItem: (id: string) => boolean;
  buyItem: (id: string) => boolean;
  cameraHolding: () => boolean;
  varNow: (name: string) => number;
  shopVisible: () => boolean;
  hierarchyCount: () => number;
  flowNodes: () => number;
  titleVisible: () => boolean;
  titlePick: (kind: 'continue' | 'new') => void;
  togglePanel: () => void;
  toggleFloat: () => void;
  panelFloating: () => boolean;
  panelMinimized: () => boolean;
  genTiles: (kind: 'maze' | 'dungeon' | 'island') => void;
  tileRows: (layer?: string) => string[] | null;
  /** 🥞 tile layers */
  setPaintLayer: (id: string) => string;
  paintLayer: () => string;
  playClip: (name: string, clip: string) => boolean;
  activeClip: (name: string) => string | null;
  librarySave: () => string;
  libraryList: () => { id: string; name: string; updated: number }[];
  libraryOpen: (id: string) => boolean;
  libraryDelete: (id: string) => void;
  /** ⬚ multi-select + 📋 clipboard */
  selectedNames: () => string[];
  selectAdd: (name: string) => boolean;
  selectAll: () => number;
  marqueeSelect: (x0: number, y0: number, x1: number, y1: number) => number;
  copySel: () => number;
  cutSel: () => number;
  pasteSel: (x?: number, y?: number) => number;
  duplicateSel: () => number;
  deleteSel: () => number;
  nudgeSel: (dx: number, dy: number) => number;
  alignSel: (edge: 'left' | 'right' | 'top' | 'bottom' | 'centerX' | 'centerY') => number;
  distributeSel: () => number;
  dragSel: (name: string, x: number, y: number) => boolean;
  inspectorTitle: () => string;
  designAt: (clientX: number, clientY: number) => { x: number; y: number };
  selectionBoxes: () => {
    ring: { x: number; y: number; w: number; h: number };
    view: { x: number; y: number; w: number; h: number };
  } | null;
  /** ⚔ enemy attack patterns */
  setAttack: (name: string, pattern: string, every: number) => boolean;
  attackOf: (name: string) => string | null;
  mobWindup: (name: string) => number;
  mobDashing: (name: string) => boolean;
  slamNow: (name: string) => number;
  liveShots: () => number;
  /** 🧰 overflow toolbar */
  toolbarOverflow: () => string[];
  toolbarOpen: () => void;
  toolbarClose: () => void;
  toolbarIsOpen: () => boolean;
  toolbarRelayout: () => void;
  onScreen: (id: string) => boolean;
}

declare global {
  interface Window {
    __studio?: StudioDebug;
  }
}
