/**
 * 🧊 The stock model catalogue — what the Model dropdown offers before
 * anyone uploads anything. Generated by scripts/make-stock-models.mjs and
 * served from public/models/; the clips listed here are the clips the
 * files actually carry, so the anim dropdowns never offer a lie.
 */
export interface StockModel {
  id: string;
  label: string;
  clips: string[];
}

export const STOCK_MODELS: readonly StockModel[] = [
  { id: 'models/blob.glb', label: '🔵 Blob', clips: ['idle', 'walk'] },
  { id: 'models/boss.glb', label: '👹 Boss golem', clips: ['idle', 'swing'] },
  { id: 'models/crate.glb', label: '📦 Crate', clips: [] },
  { id: 'models/plant.glb', label: '🌿 Plant', clips: ['idle'] },
  { id: 'models/lantern.glb', label: '🏮 Lantern', clips: ['idle'] },
];

export function stockClips(modelId: string): string[] {
  return STOCK_MODELS.find((m) => m.id === modelId)?.clips ?? [];
}
